CREATE TABLE employee
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    email        VARCHAR(255),
    phone_number VARCHAR(255),
    password     VARCHAR(255),
    CONSTRAINT pk_employee PRIMARY KEY (id)
);