ALTER TABLE employee
    ADD first_name VARCHAR(255);

ALTER TABLE employee
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE employee
    ADD last_name VARCHAR(255);

ALTER TABLE employee
    ADD password VARCHAR(255);

ALTER TABLE employee
    ADD phone_number VARCHAR(255);

ALTER TABLE employee
    ADD CONSTRAINT pk_employee PRIMARY KEY (id);

DROP TABLE employee1 CASCADE;

ALTER TABLE employee
DROP
COLUMN employeeid;

ALTER TABLE employee
DROP
COLUMN firstname;

ALTER TABLE employee
DROP
COLUMN lastname;

ALTER TABLE employee
DROP
COLUMN phonenumber;