name: Java Maven Build & test
on:
  pull_request:
jobs:
  build_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testUser
          POSTGRES_PASSWORD: testPassword
          POSTGRES_DB: testDb
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    - name: mvn clean package
      run: mvn clean package
      env:
        POSTGRES_USER: testUser
        POSTGRES_PASSWORD: testPassword
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testDb